spring:
  application:
    name: auth
  datasource:
    url: jdbc:h2:tcp://localhost/~/user
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none


jwt:
  secret: fdag32fdsavv32few89vbbafdsbaugubdsag8904fdsafdvcxcbre
  expiration: 6000000

logging:
  level:
    org.springframework.security: trace
    com.example.auth: info
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZon: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: Hi:imAuth