spring:
  application:
    name: board
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    org.hibernate.SQL: debug



server:
  port: 0
eureka:
  client:
    service-url:
      defaultZon: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: Hi:imBoard